### ISSUE TITLE
Interference with Terminal

### ISSUE THREAD

**Issue by Chiroyce1** [Sid72020123/pyTextColor#1]
Tested on macOS Big Sur 11.6.2 with the default Terminal.

After printing text with pyTextColor, the arrow keys are not usable and print out this instead

https://user-images.githubusercontent.com/97374054/150647264-e99ce360-59e3-473c-ab7b-97e55cc59bc3.mov

This is quite a big issue, since then we cannot use the arrow keys to move the cursor. I'm not sure if this is easily fixable.

**Comment by imdevarsh** [comment]
cannot reproduce, monterey 12.1 with apple default terminal and hyper, although I do have oh my zsh installed with theme "simple"

**Comment by Chiroyce1** [comment]
For some reason I cannot replicate this now as well 😬

**Comment by imdevarsh** [comment]
LOL probably just default Terminal being weird

**Comment by Sid72020123** [comment]
I just tried it with command prompt. It doesn't support ANSI Escape Sequences so this is the output:
![image](https://user-images.githubusercontent.com/70252606/150670287-c15e6ef0-9258-4e28-99e6-a4b79d241e95.png)

**Comment by Sid72020123** [comment]
After pressing some arrow keys, it works fine for me. Let me check on others...

**Comment by Sid72020123** [comment]
Output on Windows Powershell:
![image](https://user-images.githubusercontent.com/70252606/150670427-2adfdd19-f5bb-4544-a928-5beb8712a46a.png)

**Comment by Sid72020123** [comment]
> Tested on macOS Big Sur 11.6.2 with the default Terminal.
> 
> After printing text with pyTextColor, the arrow keys are not usable and print out this instead
> 
>  Screen.Recording.2022-01-22.at.10.01.23.PM.mov 
> This is quite a big issue, since then we cannot use the arrow keys to move the cursor. I'm not sure if this is easily fixable.

After using the "print(text)" function, the text should have been printed out in the Terminal. If the terminal doesn't support ANSI then it should print out the escape characters. So this means that pyTextColor in your Terminal doesn't work :(
Have you tried using tinted library?

**Comment by imdevarsh** [comment]
You should attempt to use colorama on windows

**Comment by Sid72020123** [comment]
Yes...

**Comment by Sid72020123** [comment]
It also works in PyCharm:
![image](https://user-images.githubusercontent.com/70252606/150670747-c2abff14-cee8-4894-9854-05cd81ee3bfe.png)
The above picture is the output made using my work-in-progress library: pyLogger

**Comment by Chiroyce1** [comment]
The problem isn't there now - I have no clue why. But I did find a new one. #2

**Comment by Sid72020123** [comment]
I saw that. I am finding a solution for that...

**Comment by Chiroyce1** [comment]
Closing this since this doesn't seem like it was caused by pyTextColor.

**Comment by kccuber-scratch** [comment]
this is a weird thing with python that i can reproduce if im trying to install arch linux through archinstall, which is also python, so i guess it's a python thing
